In [ ]:
# importamos las librerías que necesitamos

# Tratamiento de datos
# -----------------------------------------------------------------------
import pandas as pd
import numpy as np

# Imputación de nulos usando métodos avanzados estadísticos
# -----------------------------------------------------------------------
from sklearn.impute import SimpleImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.impute import KNNImputer

# Librerías de visualización
# -----------------------------------------------------------------------
import seaborn as sns
import matplotlib.pyplot as plt
# Configuración
# -----------------------------------------------------------------------
pd.set_option('display.max_columns', None) # para poder visualizar todas las columnas de los DataFrames

In [12]:
df = pd.read_csv("world_data_nuevo.csv")
df.head(5)

,Unnamed: 0.1,Unnamed: 0,country,density,abbreviation,agricultural_land(_%),land_area,armed_forces_size,birth_rate,calling_code,capital/major_city,co2-emissions,cpi,cpi_change_,currency-code,fertility_rate,forested_area_,gasoline_price,gdp,gross_primary_education_enrollment_,gross_tertiary_education_enrollment_,infant_mortality,largest_city,life_expectancy,maternal_mortality_ratio,minimum_wage,official_language,out_of_pocket_health_expenditure,physicians_per_thousand,population,population_labor_force_participation_,tax_revenue_,total_tax_rate,unemployment_rate,urban_population,latitud,longitud,continent,tax_density_ratio
0,0,0,Afghanistan,60.0,AF,58.1,NaN,NaN,32.49,93.0,Kabul,NaN,149.90,2.3,AFN,4.47,2.1,0.70,NaN,104.0,9.7,47.9,Kabul,64.5,638.0,0.43,Pashto,78.4,0.28,NaN,48.9,9.3,71.4,11.12,NaN,NaN,NaN,NaN,1.190000
1,1,1,Albania,105.0,AL,43.1,NaN,NaN,11.78,355.0,Tirana,NaN,119.05,1.4,ALL,1.62,28.1,1.36,NaN,107.0,55.0,7.8,Tirana,78.5,15.0,1.12,Albanian,56.9,1.20,NaN,55.7,18.6,36.6,12.33,NaN,NaN,NaN,NaN,0.348571
2,2,2,Algeria,18.0,DZ,17.4,NaN,NaN,24.28,213.0,Algiers,NaN,151.36,2.0,DZD,3.02,0.8,0.28,NaN,109.9,51.4,20.1,Algiers,76.7,112.0,0.95,Arabic,28.1,1.72,NaN,41.2,37.2,66.1,11.70,NaN,NaN,NaN,NaN,3.672222
3,3,3,Andorra,164.0,AD,40.0,468.0,NaN,7.20,376.0,Andorra la Vella,469.0,NaN,NaN,EUR,1.27,34.0,1.51,NaN,106.4,NaN,2.7,Andorra la Vella,NaN,NaN,6.63,Catalan,36.4,3.33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,4,Angola,26.0,AO,47.5,NaN,NaN,40.73,244.0,Luanda,NaN,261.73,17.1,AOA,5.52,46.3,0.97,NaN,113.5,9.3,51.6,Luanda,60.8,241.0,0.71,Portuguese,33.4,0.21,NaN,77.5,9.2,49.1,6.89,NaN,NaN,NaN,NaN,1.888462

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 39 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Unnamed: 0.1                           195 non-null    int64
 1   Unnamed: 0                             195 non-null    int64
 2   country                                195 non-null    object
 3   density                                188 non-null    float64
 4   abbreviation                           188 non-null    object
 5   agricultural_land(_%)                  188 non-null    float64
 6   land_area                              25 non-null     float64
 7   armed_forces_size                      5 non-null      float64
 8   birth_rate                             189 non-null    float64
 9   calling_code                           194 non-null    float64
 10  capital/major_city                     192 non-null    object
 11  co2-emissions                          30 non-null     float64
 12  cpi                                    175 non-null    float64
 13  cpi_change_                            179 non-null    float64
 14  currency-code                          180 non-null    object
 15  fertility_rate                         188 non-null    float64
 16  forested_area_                         188 non-null    float64
 17  gasoline_price                         175 non-null    float64
 18  gdp                                    0 non-null      float64
 19  gross_primary_education_enrollment_    188 non-null    float64
 20  gross_tertiary_education_enrollment_   183 non-null    float64
 21  infant_mortality                       189 non-null    float64
 22  largest_city                           189 non-null    object
 23  life_expectancy                        187 non-null    float64
 24  maternal_mortality_ratio               181 non-null    float64
 25  minimum_wage                           150 non-null    float64
 26  official_language                      190 non-null    object
 27  out_of_pocket_health_expenditure       188 non-null    float64
 28  physicians_per_thousand                188 non-null    float64
 29  population                             1 non-null      float64
 30  population_labor_force_participation_  176 non-null    float64
 31  tax_revenue_                           169 non-null    float64
 32  total_tax_rate                         183 non-null    float64
 33  unemployment_rate                      176 non-null    float64
 34  urban_population                       0 non-null      float64
 35  latitud                                0 non-null      float64
 36  longitud                               0 non-null      float64
 37  continent                              2 non-null      object
 38  tax_density_ratio                      178 non-null    float64
dtypes: float64(30), int64(2), object(7)
memory usage: 59.5+ KB

In [14]:
df.isnull().sum() / df.shape[0]

Unnamed: 0.1                             0.000000
Unnamed: 0                               0.000000
country                                  0.000000
density                                  0.035897
abbreviation                             0.035897
agricultural_land(_%)                    0.035897
land_area                                0.871795
armed_forces_size                        0.974359
birth_rate                               0.030769
calling_code                             0.005128
capital/major_city                       0.015385
co2-emissions                            0.846154
cpi                                      0.102564
cpi_change_                              0.082051
currency-code                            0.076923
fertility_rate                           0.035897
forested_area_                           0.035897
gasoline_price                           0.102564
gdp                                      1.000000
gross_primary_education_enrollment_      0.035897
gross_tertiary_education_enrollment_     0.061538
infant_mortality                         0.030769
largest_city                             0.030769
life_expectancy                          0.041026
maternal_mortality_ratio                 0.071795
minimum_wage                             0.230769
official_language                        0.025641
out_of_pocket_health_expenditure         0.035897
physicians_per_thousand                  0.035897
population                               0.994872
population_labor_force_participation_    0.097436
tax_revenue_                             0.133333
total_tax_rate                           0.061538
unemployment_rate                        0.097436
urban_population                         1.000000
latitud                                  1.000000
longitud                                 1.000000
continent                                0.989744
tax_density_ratio                        0.087179
dtype: float64

In [15]:
col_eliminar = ['land_area','armed_forces_size','co2-emissions','gdp','population','urban_population', 'latitud', 'longitud','continent']

In [16]:
df.drop(columns= col_eliminar, inplace = True)

In [17]:
# Obtenemos la lista de columnas numericas que tienen nulos
nulos_esta_num = df[df.columns[df.isnull().any()]].select_dtypes(include = np.number).columns
print("Las columnas numéricas que tienen nulos son : \n ")
print(nulos_esta_num)

Las columnas numéricas que tienen nulos son :

Index(['density', 'agricultural_land(_%)', 'birth_rate', 'calling_code', 'cpi',
       'cpi_change_', 'fertility_rate', 'forested_area_', 'gasoline_price',
       'gross_primary_education_enrollment_',
       'gross_tertiary_education_enrollment_', 'infant_mortality',
       'life_expectancy', 'maternal_mortality_ratio', 'minimum_wage',
       'out_of_pocket_health_expenditure', 'physicians_per_thousand',
       'population_labor_force_participation_', 'tax_revenue_',
       'total_tax_rate', 'unemployment_rate', 'tax_density_ratio'],
      dtype='object')

In [18]:
# calcular el número de nulos que tenemos en cada una de las columnas numericas
df[nulos_esta_num].isnull().sum() / df.shape[0]

density                                  0.035897
agricultural_land(_%)                    0.035897
birth_rate                               0.030769
calling_code                             0.005128
cpi                                      0.102564
cpi_change_                              0.082051
fertility_rate                           0.035897
forested_area_                           0.035897
gasoline_price                           0.102564
gross_primary_education_enrollment_      0.035897
gross_tertiary_education_enrollment_     0.061538
infant_mortality                         0.030769
life_expectancy                          0.041026
maternal_mortality_ratio                 0.071795
minimum_wage                             0.230769
out_of_pocket_health_expenditure         0.035897
physicians_per_thousand                  0.035897
population_labor_force_participation_    0.097436
tax_revenue_                             0.133333
total_tax_rate                           0.061538
unemployment_rate                        0.097436
tax_density_ratio                        0.087179
dtype: float64

In [20]:
def valores_unicos_por_columna(dataframe): 
    valores_unicos = {} 
    for columna in dataframe.columns: 
        valores_unicos[columna] = dataframe[columna].unique().tolist() 
    return valores_unicos

In [29]:
valore_num = valores_unicos_por_columna(df[nulos_esta_num])

In [31]:
valore_num

{'density': [60.0,
  105.0,
  18.0,
  164.0,
  26.0,
  223.0,
  17.0,
  104.0,
  3.0,
  109.0,
  123.0,
  39.0,
  nan,
  668.0,
  47.0,
  383.0,
  108.0,
  20.0,
  11.0,
  64.0,
  4.0,
  25.0,
  83.0,
  76.0,
  463.0,
  138.0,
  95.0,
  56.0,
  8.0,
  13.0,
  153.0,
  46.0,
  467.0,
  16.0,
  100.0,
  73.0,
  106.0,
  131.0,
  139.0,
  40.0,
  137.0,
  43.0,
  96.0,
  225.0,
  71.0,
  103.0,
  313.0,
  50.0,
  35.0,
  31.0,
  67.0,
  115.0,
  49.0,
  119.0,
  9.0,
  239.0,
  57.0,
  240.0,
  81.0,
  331.0,
  167.0,
  53.0,
  70.0,
  414.0,
  89.0,
  107.0,
  464.0,
  151.0,
  52.0,
  93.0,
  72.0,
  400.0,
  206.0,
  273.0,
  347.0,
  7.0,
  94.0,
  147.0,
  34.0,
  32.0,
  30.0,
  667.0,
  238.0,
  242.0,
  48.0,
  203.0,
  99.0,
  329.0,
  5.0,
  626.0,
  66.0,
  784.0,
  2.0,
  541.0,
  508.0,
  55.0,
  19.0,
  226.0,
  214.0,
  15.0,
  287.0,
  847.0,
  58.0,
  368.0,
  124.0,
  111.0,
  248.0,
  84.0,
  525.0,
  205.0,
  301.0,
  284.0,
  566.0,
  228.0,
  87.0,
  114.0,
  527.0,
  341.0,
  219.0,
  68.0,
  152.0,
  110.0,
  393.0,
  229.0,
  75.0,
  118.0,
  281.0,
  36.0,
  79.0,
  314.0,
  38.0],
 'agricultural_land(_%)': [58.1,
  43.1,
  17.4,
  40.0,
  47.5,
  20.5,
  54.3,
  58.9,
  48.2,
  32.4,
  57.7,
  1.4,
  11.1,
  70.6,
  23.3,
  42.0,
  44.6,
  7.0,
  33.3,
  13.6,
  34.8,
  45.6,
  33.9,
  2.7,
  46.3,
  44.2,
  79.2,
  64.8,
  19.6,
  30.9,
  20.6,
  6.9,
  8.2,
  39.7,
  21.2,
  56.2,
  40.3,
  71.5,
  31.1,
  34.5,
  27.6,
  59.9,
  12.2,
  45.2,
  11.6,
  62.0,
  73.4,
  48.7,
  22.2,
  3.8,
  76.4,
  10.1,
  75.2,
  23.1,
  nan,
  36.3,
  7.5,
  52.4,
  20.0,
  59.8,
  47.7,
  69.0,
  47.6,
  23.5,
  36.0,
  59.0,
  58.0,
  8.6,
  66.8,
  28.9,
  58.4,
  18.7,
  60.4,
  31.5,
  28.2,
  21.4,
  64.5,
  24.6,
  43.2,
  41.0,
  12.3,
  12.0,
  80.4,
  48.5,
  8.4,
  55.0,
  10.3,
  64.3,
  77.6,
  28.0,
  8.7,
  32.2,
  47.2,
  53.7,
  71.2,
  61.4,
  26.3,
  33.8,
  63.9,
  38.5,
  42.4,
  54.6,
  31.4,
  74.2,
  19.0,
  68.5,
  63.5,
  19.5,
  47.1,
  28.7,
  53.3,
  40.5,
  42.1,
  36.1,
  77.7,
  21.8,
  4.6,
  47.8,
  10.9,
  30.4,
  2.6,
  55.1,
  18.5,
  41.7,
  46.9,
  39.5,
  5.8,
  58.8,
  13.3,
  25.6,
  12.4,
  16.7,
  50.7,
  80.8,
  46.1,
  39.3,
  3.4,
  54.7,
  0.9,
  39.2,
  30.7,
  3.9,
  70.3,
  79.8,
  52.6,
  43.7,
  0.6,
  7.4,
  38.4,
  75.8,
  34.1,
  44.8,
  43.3,
  70.2,
  45.8,
  10.5,
  49.8,
  72.0,
  60.0,
  71.9,
  71.7,
  5.5,
  44.4,
  82.6,
  62.9,
  15.3,
  24.5,
  32.1,
  41.9],
 'birth_rate': [32.49,
  11.78,
  24.28,
  7.2,
  40.73,
  15.33,
  17.02,
  13.99,
  12.6,
  9.7,
  14.0,
  13.97,
  18.18,
  10.65,
  9.9,
  10.3,
  20.79,
  36.22,
  17.26,
  21.75,
  8.11,
  24.82,
  13.92,
  14.9,
  8.9,
  37.93,
  39.01,
  35.74,
  19.49,
  22.46,
  35.39,
  10.1,
  35.35,
  42.17,
  12.43,
  10.9,
  14.88,
  31.88,
  32.86,
  9.0,
  10.17,
  10.46,
  10.7,
  41.18,
  10.6,
  21.47,
  12.0,
  19.51,
  19.72,
  26.38,
  18.25,
  33.24,
  30.3,
  nan,
  32.34,
  21.28,
  8.6,
  11.3,
  31.61,
  38.54,
  13.47,
  9.5,
  29.41,
  8.1,
  16.47,
  24.56,
  36.36,
  35.13,
  19.97,
  24.35,
  21.6,
  9.6,
  17.86,
  18.07,
  18.78,
  29.08,
  12.5,
  20.8,
  7.3,
  16.1,
  7.4,
  21.98,
  21.77,
  28.75,
  27.89,
  13.94,
  27.1,
  23.55,
  10.0,
  17.55,
  26.81,
  33.04,
  18.83,
  32.66,
  34.12,
  16.75,
  14.2,
  41.54,
  9.2,
  29.03,
  33.69,
  10.2,
  17.6,
  22.82,
  5.9,
  24.13,
  11.73,
  18.94,
  37.52,
  28.64,
  19.89,
  11.98,
  20.64,
  46.08,
  37.91,
  13.89,
  10.4,
  19.19,
  28.25,
  18.98,
  27.07,
  20.57,
  17.95,
  20.55,
  8.5,
  9.54,
  11.5,
  31.7,
  14.24,
  24.38,
  6.8,
  31.54,
  17.8,
  34.52,
  17.1,
  33.41,
  8.8,
  9.4,
  32.44,
  41.75,
  20.51,
  6.4,
  35.01,
  7.9,
  15.83,
  32.18,
  18.54,
  11.4,
  23.69,
  30.76,
  36.7,
  10.34,
  29.42,
  33.11,
  24.3,
  12.94,
  17.56,
  16.03,
  23.83,
  38.14,
  8.7,
  10.33,
  11.0,
  11.6,
  13.86,
  23.3,
  29.6,
  17.88,
  30.45,
  36.19,
  30.68],
 'calling_code': [93.0,
  355.0,
  213.0,
  376.0,
  244.0,
  1.0,
  54.0,
  374.0,
  61.0,
  43.0,
  994.0,
  973.0,
  880.0,
  375.0,
  32.0,
  501.0,
  229.0,
  975.0,
  591.0,
  387.0,
  267.0,
  55.0,
  673.0,
  359.0,
  226.0,
  257.0,
  225.0,
  238.0,
  855.0,
  237.0,
  236.0,
  235.0,
  56.0,
  86.0,
  57.0,
  269.0,
  242.0,
  506.0,
  385.0,
  53.0,
  357.0,
  420.0,
  243.0,
  45.0,
  253.0,
  593.0,
  20.0,
  503.0,
  240.0,
  291.0,
  372.0,
  268.0,
  251.0,
  679.0,
  358.0,
  33.0,
  241.0,
  220.0,
  995.0,
  49.0,
  233.0,
  30.0,
  502.0,
  224.0,
  245.0,
  592.0,
  509.0,
  379.0,
  504.0,
  36.0,
  354.0,
  91.0,
  62.0,
  98.0,
  964.0,
  353.0,
  972.0,
  39.0,
  1876.0,
  81.0,
  962.0,
  7.0,
  254.0,
  686.0,
  965.0,
  996.0,
  856.0,
  371.0,
  961.0,
  266.0,
  231.0,
  218.0,
  423.0,
  370.0,
  352.0,
  261.0,
  265.0,
  60.0,
  960.0,
  223.0,
  356.0,
  692.0,
  222.0,
  230.0,
  52.0,
  691.0,
  373.0,
  377.0,
  976.0,
  382.0,
  212.0,
  258.0,
  95.0,
  264.0,
  674.0,
  977.0,
  31.0,
  64.0,
  505.0,
  227.0,
  234.0,
  850.0,
  389.0,
  47.0,
  968.0,
  92.0,
  680.0,
  nan,
  507.0,
  675.0,
  595.0,
  51.0,
  63.0,
  48.0,
  351.0,
  974.0,
  40.0,
  250.0,
  685.0,
  378.0,
  239.0,
  966.0,
  221.0,
  381.0,
  248.0,
  232.0,
  65.0,
  421.0,
  386.0,
  677.0,
  252.0,
  27.0,
  82.0,
  211.0,
  34.0,
  94.0,
  249.0,
  597.0,
  46.0,
  41.0,
  963.0,
  992.0,
  255.0,
  66.0,
  670.0,
  228.0,
  676.0,
  216.0,
  90.0,
  993.0,
  688.0,
  256.0,
  380.0,
  971.0,
  44.0,
  598.0,
  998.0,
  678.0,
  58.0,
  84.0,
  967.0,
  260.0,
  263.0],
 'cpi': [149.9,
  119.05,
  151.36,
  nan,
  261.73,
  113.81,
  232.75,
  129.18,
  119.8,
  118.06,
  156.32,
  116.22,
  117.59,
  179.68,
  134.09,
  117.11,
  105.68,
  110.71,
  167.18,
  148.32,
  104.9,
  149.75,
  167.4,
  99.03,
  114.42,
  106.58,
  182.11,
  111.61,
  110.5,
  127.63,
  118.65,
  116.76,
  186.86,
  117.7,
  131.91,
  125.08,
  140.95,
  103.62,
  124.74,
  128.85,
  109.82,
  102.51,
  116.48,
  133.85,
  110.35,
  120.25,
  103.87,
  135.5,
  124.14,
  288.57,
  111.23,
  124.35,
  122.14,
  143.86,
  132.3,
  112.33,
  110.05,
  122.19,
  172.73,
  133.61,
  112.85,
  268.36,
  101.87,
  107.43,
  142.92,
  262.95,
  111.65,
  116.19,
  179.29,
  150.34,
  121.64,
  129.0,
  180.44,
  151.18,
  550.93,
  119.86,
  108.15,
  110.62,
  162.47,
  105.48,
  125.6,
  182.75,
  180.51,
  99.55,
  126.6,
  155.68,
  135.87,
  116.86,
  130.02,
  155.86,
  223.13,
  125.71,
  118.38,
  115.09,
  184.33,
  418.34,
  121.46,
  99.7,
  108.73,
  113.45,
  135.02,
  129.91,
  141.54,
  112.1,
  166.2,
  195.76,
  116.32,
  111.07,
  182.31,
  168.18,
  157.97,
  188.73,
  115.91,
  114.24,
  162.74,
  109.32,
  267.51,
  120.27,
  113.53,
  182.32,
  118.17,
  122.07,
  155.99,
  143.82,
  129.78,
  129.61,
  114.11,
  115.38,
  123.78,
  180.75,
  151.09,
  104.57,
  110.13,
  109.67,
  117.56,
  110.63,
  185.09,
  118.4,
  109.25,
  144.0,
  129.96,
  234.16,
  114.41,
  115.34,
  111.05,
  133.06,
  158.93,
  115.16,
  110.96,
  155.53,
  294.66,
  110.51,
  143.2,
  148.57,
  187.43,
  113.27,
  145.38,
  113.3,
  121.09,
  141.75,
  155.33,
  234.44,
  173.87,
  281.66,
  114.52,
  119.62,
  117.24,
  202.92,
  117.13,
  163.52,
  157.58,
  212.31,
  105.51],
 'cpi_change_': [2.3,
  1.4,
  2.0,
  nan,
  17.1,
  1.2,
  53.5,
  1.6,
  1.5,
  2.6,
  2.5,
  2.1,
  5.6,
  4.1,
  -0.9,
  2.7,
  1.8,
  0.6,
  2.8,
  3.7,
  -0.4,
  3.1,
  -3.2,
  -0.7,
  1.1,
  1.9,
  37.1,
  -1.0,
  2.9,
  3.5,
  -4.3,
  2.2,
  0.8,
  0.3,
  3.3,
  1.0,
  9.2,
  0.1,
  15.8,
  7.1,
  4.9,
  7.2,
  0.2,
  9.5,
  12.5,
  4.4,
  3.0,
  7.7,
  39.9,
  0.4,
  0.9,
  3.9,
  0.5,
  5.2,
  4.7,
  23.6,
  1.7,
  9.4,
  0.7,
  -1.7,
  3.6,
  4.8,
  7.3,
  8.8,
  5.4,
  -2.5,
  11.4,
  10.6,
  1.3,
  3.8,
  4.5,
  3.4,
  7.9,
  -1.2,
  14.8,
  187.9,
  51.0,
  22.0,
  36.7,
  6.0,
  7.4,
  6.7,
  15.2,
  -1.9,
  7.5,
  254.9,
  8.1],
 'fertility_rate': [4.47,
  1.62,
  3.02,
  1.27,
  5.52,
  1.99,
  2.26,
  1.76,
  1.74,
  1.47,
  1.73,
  1.75,
  2.04,
  1.45,
  2.31,
  4.84,
  1.98,
  2.73,
  2.87,
  1.85,
  1.56,
  5.19,
  5.41,
  4.65,
  2.27,
  2.5,
  4.57,
  1.5,
  4.72,
  5.75,
  1.65,
  1.69,
  1.81,
  4.21,
  4.43,
  1.33,
  5.92,
  1.9,
  2.35,
  2.43,
  3.33,
  4.51,
  4.06,
  1.59,
  nan,
  4.25,
  2.77,
  1.41,
  1.88,
  3.97,
  5.22,
  2.06,
  3.87,
  1.35,
  4.7,
  4.48,
  2.46,
  2.94,
  1.54,
  1.71,
  2.22,
  2.14,
  3.67,
  3.09,
  1.29,
  1.42,
  2.76,
  2.84,
  3.49,
  3.57,
  2.08,
  3.3,
  2.67,
  1.6,
  2.09,
  3.14,
  4.32,
  2.24,
  1.44,
  1.63,
  1.37,
  4.08,
  2.0,
  1.87,
  5.88,
  1.23,
  4.05,
  4.56,
  2.13,
  3.05,
  1.26,
  2.9,
  2.42,
  4.85,
  2.15,
  3.4,
  1.92,
  2.4,
  6.91,
  5.39,
  2.89,
  3.51,
  2.21,
  3.56,
  2.25,
  2.58,
  1.46,
  1.38,
  1.57,
  4.04,
  2.11,
  1.89,
  3.88,
  2.32,
  4.63,
  1.49,
  2.41,
  4.26,
  1.14,
  1.52,
  4.4,
  6.07,
  0.98,
  2.2,
  4.41,
  2.81,
  3.59,
  4.89,
  1.53,
  4.02,
  2.07,
  2.79,
  4.96,
  1.3,
  1.68,
  1.97,
  3.78,
  2.05,
  3.79,
  3.62],
 'forested_area_': [2.1,
  28.1,
  0.8,
  34.0,
  46.3,
  22.3,
  9.8,
  11.7,
  16.3,
  46.9,
  14.1,
  51.4,
  11.0,
  14.7,
  42.6,
  22.6,
  59.7,
  37.8,
  72.5,
  50.3,
  42.7,
  18.9,
  58.9,
  72.1,
  35.4,
  19.3,
  10.9,
  32.7,
  22.5,
  52.9,
  39.3,
  38.2,
  35.6,
  3.8,
  24.3,
  22.4,
  52.7,
  19.7,
  65.4,
  54.6,
  34.4,
  31.3,
  18.7,
  34.6,
  67.2,
  0.2,
  57.4,
  41.7,
  50.2,
  0.1,
  12.6,
  55.5,
  14.9,
  51.3,
  nan,
  12.5,
  55.9,
  73.1,
  31.2,
  90.0,
  48.4,
  40.6,
  41.2,
  31.7,
  50.0,
  25.8,
  69.8,
  83.9,
  3.5,
  40.0,
  22.9,
  0.5,
  23.8,
  49.9,
  6.6,
  1.9,
  7.7,
  31.8,
  30.9,
  68.5,
  1.1,
  1.2,
  7.8,
  15.0,
  0.4,
  3.3,
  82.1,
  54.0,
  13.4,
  1.6,
  43.1,
  34.8,
  35.7,
  21.4,
  33.2,
  67.6,
  70.2,
  19.0,
  33.9,
  91.9,
  8.0,
  61.5,
  48.0,
  43.6,
  8.3,
  25.4,
  11.2,
  38.6,
  25.9,
  0.9,
  7.2,
  40.7,
  0.0,
  87.6,
  61.9,
  74.1,
  37.7,
  57.7,
  27.8,
  30.1,
  49.8,
  42.3,
  69.2,
  60.4,
  55.8,
  42.8,
  31.1,
  88.4,
  23.1,
  40.4,
  62.0,
  77.9,
  10.0,
  7.6,
  63.4,
  36.9,
  32.9,
  8.1,
  98.3,
  68.9,
  2.7,
  3.0,
  51.6,
  32.2,
  45.4,
  3.1,
  46.0,
  6.8,
  15.4,
  8.8,
  33.3,
  9.7,
  16.7,
  4.6,
  13.1,
  10.7,
  7.5,
  36.1,
  48.1,
  1.0,
  65.2,
  35.5],
 'gasoline_price': [0.7,
  1.36,
  0.28,
  1.51,
  0.97,
  0.99,
  1.1,
  0.77,
  0.93,
  1.2,
  0.56,
  0.92,
  0.43,
  1.12,
  1.81,
  0.6,
  1.43,
  1.13,
  0.72,
  0.98,
  0.71,
  1.05,
  1.02,
  0.37,
  1.11,
  1.21,
  0.9,
  1.03,
  0.81,
  1.41,
  0.78,
  0.96,
  0.68,
  nan,
  1.26,
  1.4,
  1.23,
  1.17,
  1.49,
  1.55,
  1.32,
  1.07,
  0.61,
  0.4,
  0.83,
  2.0,
  1.14,
  0.75,
  0.82,
  1.45,
  1.39,
  1.18,
  0.76,
  1.54,
  0.79,
  1.69,
  0.63,
  1.37,
  1.57,
  1.61,
  1.06,
  0.42,
  0.95,
  0.35,
  1.16,
  0.74,
  0.8,
  0.11,
  1.74,
  1.19,
  1.15,
  0.45,
  1.63,
  1.44,
  0.73,
  0.65,
  0.54,
  0.91,
  1.68,
  0.88,
  0.46,
  0.58,
  1.78,
  1.04,
  0.86,
  0.59,
  1.3,
  0.24,
  1.08,
  1.25,
  1.22,
  1.29,
  1.42,
  0.87,
  0.29,
  0.94,
  0.49,
  1.46,
  1.5,
  1.31,
  0.0,
  1.34],
 'gross_primary_education_enrollment_': [104.0,
  107.0,
  109.9,
  106.4,
  113.5,
  105.0,
  109.7,
  92.7,
  100.3,
  103.1,
  99.7,
  81.4,
  99.4,
  116.5,
  100.5,
  103.9,
  111.7,
  122.0,
  100.1,
  98.2,
  nan,
  103.2,
  115.4,
  89.3,
  96.1,
  121.4,
  99.8,
  107.4,
  103.4,
  100.9,
  102.0,
  86.8,
  101.4,
  100.2,
  114.5,
  99.5,
  106.6,
  113.3,
  96.5,
  101.9,
  99.3,
  100.7,
  108.0,
  101.3,
  75.3,
  114.7,
  105.7,
  103.3,
  106.3,
  94.8,
  61.8,
  68.4,
  97.2,
  101.0,
  102.5,
  139.9,
  98.0,
  98.6,
  104.8,
  99.6,
  106.9,
  91.5,
  118.7,
  97.8,
  113.6,
  100.8,
  100.4,
  113.0,
  110.7,
  108.7,
  104.9,
  91.0,
  98.8,
  81.5,
  104.4,
  92.4,
  107.6,
  102.4,
  95.1,
  120.9,
  85.1,
  109.0,
  104.7,
  102.3,
  142.5,
  105.3,
  97.1,
  75.6,
  84.7,
  99.9,
  101.1,
  105.8,
  90.6,
  100.0,
  113.9,
  112.6,
  112.3,
  124.2,
  142.1,
  104.2,
  120.6,
  74.7,
  112.8,
  94.3,
  94.4,
  108.5,
  107.5,
  106.2,
  103.8,
  85.2,
  102.6,
  133.0,
  113.4,
  110.5,
  108.1,
  106.8,
  81.0,
  100.6,
  98.7,
  23.4,
  98.1,
  73.0,
  102.7,
  76.8,
  108.8,
  126.6,
  105.2,
  81.7,
  94.2,
  115.3,
  123.8,
  116.3,
  93.2,
  88.4,
  86.0,
  99.0,
  108.4,
  101.2,
  101.8,
  109.3,
  110.6,
  93.6],
 'gross_tertiary_education_enrollment_': [9.7,
  55.0,
  51.4,
  nan,
  9.3,
  24.8,
  90.0,
  54.6,
  113.1,
  85.1,
  27.7,
  15.1,
  50.5,
  20.6,
  65.4,
  87.4,
  79.7,
  24.7,
  12.3,
  15.6,
  23.3,
  24.9,
  51.3,
  31.4,
  71.0,
  6.5,
  6.1,
  23.6,
  13.7,
  12.8,
  68.9,
  3.0,
  3.3,
  88.5,
  50.6,
  55.3,
  9.0,
  12.7,
  55.2,
  67.9,
  41.4,
  75.9,
  64.1,
  6.6,
  80.6,
  5.3,
  7.2,
  59.9,
  44.9,
  35.2,
  29.4,
  1.9,
  3.4,
  69.6,
  8.1,
  16.1,
  88.2,
  65.6,
  8.3,
  2.7,
  63.9,
  70.2,
  15.7,
  136.6,
  104.6,
  21.8,
  11.6,
  2.6,
  1.1,
  26.2,
  48.5,
  71.8,
  28.1,
  36.3,
  68.1,
  16.2,
  77.8,
  63.4,
  61.9,
  27.1,
  63.2,
  34.4,
  61.7,
  11.5,
  54.4,
  41.3,
  15.0,
  88.1,
  26.3,
  10.2,
  11.9,
  60.5,
  35.6,
  72.4,
  19.2,
  5.4,
  0.8,
  45.1,
  31.2,
  4.5,
  54.3,
  23.7,
  5.0,
  40.6,
  40.2,
  14.1,
  39.8,
  56.1,
  35.9,
  7.3,
  18.8,
  22.9,
  12.4,
  85.0,
  82.0,
  17.4,
  4.4,
  27.0,
  38.0,
  54.7,
  47.8,
  1.8,
  34.6,
  70.7,
  35.5,
  67.8,
  17.9,
  49.4,
  81.9,
  6.7,
  86.7,
  7.6,
  42.5,
  13.4,
  68.0,
  67.2,
  17.1,
  2.0,
  84.8,
  46.6,
  78.6,
  2.5,
  22.4,
  94.3,
  88.9,
  19.6,
  16.9,
  12.6,
  67.0,
  59.6,
  40.1,
  31.3,
  4.0,
  49.3,
  17.8,
  14.5,
  6.4,
  12.0,
  31.7,
  23.9,
  8.0,
  4.8,
  82.7,
  36.8,
  60.0,
  63.1,
  10.1,
  4.7,
  79.3,
  28.5,
  4.1,
  10.0],
 'infant_mortality': [47.9,
  7.8,
  20.1,
  2.7,
  51.6,
  5.0,
  8.8,
  11.0,
  3.1,
  2.9,
  19.2,
  8.3,
  6.1,
  25.1,
  11.3,
  2.6,
  11.2,
  60.5,
  24.8,
  21.8,
  30.0,
  12.8,
  9.8,
  5.9,
  49.0,
  41.0,
  59.4,
  16.7,
  24.0,
  50.6,
  4.3,
  84.5,
  71.4,
  6.2,
  7.4,
  12.2,
  51.3,
  36.2,
  7.6,
  4.0,
  3.7,
  1.9,
  68.2,
  3.6,
  49.8,
  32.9,
  24.1,
  18.1,
  11.8,
  62.6,
  31.3,
  2.1,
  nan,
  39.1,
  21.6,
  1.4,
  3.4,
  32.7,
  39.0,
  8.7,
  34.9,
  13.7,
  22.1,
  64.9,
  54.0,
  49.5,
  15.1,
  1.5,
  29.9,
  21.1,
  12.4,
  22.5,
  3.0,
  1.8,
  13.9,
  30.6,
  41.2,
  6.7,
  16.9,
  37.6,
  3.3,
  6.4,
  65.7,
  53.5,
  10.2,
  38.2,
  35.3,
  62.0,
  27.4,
  51.5,
  13.6,
  25.6,
  14.0,
  2.3,
  36.8,
  29.0,
  26.7,
  4.7,
  15.7,
  48.0,
  75.7,
  57.2,
  16.6,
  13.1,
  38.0,
  17.2,
  11.1,
  3.8,
  5.8,
  27.0,
  14.9,
  14.8,
  1.7,
  24.4,
  6.0,
  31.8,
  4.8,
  78.5,
  4.6,
  17.1,
  76.6,
  28.5,
  63.7,
  2.5,
  42.1,
  2.2,
  30.4,
  39.3,
  47.4,
  13.4,
  16.4,
  14.6,
  9.1,
  20.6,
  33.8,
  7.5,
  6.5,
  5.6,
  19.1,
  22.3,
  21.4,
  16.5,
  42.9,
  40.4,
  33.9],
 'life_expectancy': [64.5,
  78.5,
  76.7,
  nan,
  60.8,
  76.9,
  76.5,
  74.9,
  82.7,
  81.6,
  72.9,
  73.8,
  77.2,
  72.3,
  79.1,
  74.2,
  74.5,
  61.5,
  71.5,
  71.2,
  77.3,
  69.3,
  75.7,
  61.2,
  57.4,
  72.8,
  69.6,
  58.9,
  81.9,
  52.8,
  54.0,
  80.0,
  77.0,
  77.1,
  64.1,
  64.3,
  80.1,
  78.1,
  78.7,
  80.8,
  79.0,
  60.4,
  81.0,
  66.6,
  76.6,
  73.9,
  76.8,
  71.8,
  73.1,
  58.4,
  65.9,
  78.2,
  66.2,
  67.3,
  81.7,
  82.5,
  61.7,
  73.6,
  80.9,
  63.8,
  81.3,
  72.4,
  74.1,
  58.0,
  69.8,
  63.7,
  75.1,
  75.8,
  69.4,
  70.5,
  82.3,
  82.8,
  82.9,
  74.4,
  84.2,
  73.2,
  66.3,
  68.1,
  75.4,
  71.4,
  67.6,
  74.7,
  78.9,
  53.7,
  72.7,
  83.0,
  82.1,
  66.7,
  76.0,
  78.6,
  65.2,
  64.7,
  75.0,
  67.8,
  69.7,
  60.2,
  66.9,
  63.4,
  81.8,
  74.3,
  62.0,
  54.3,
  72.1,
  77.6,
  67.1,
  69.1,
  78.3,
  71.1,
  68.7,
  71.3,
  76.1,
  85.4,
  70.2,
  67.7,
  75.5,
  83.1,
  57.1,
  63.9,
  82.6,
  57.6,
  83.3,
  65.1,
  71.6,
  83.6,
  70.9,
  65.0,
  70.8,
  73.4,
  77.4,
  63.0,
  77.8,
  70.3,
  75.3,
  66.1,
  63.5],
 'maternal_mortality_ratio': [638.0,
  15.0,
  112.0,
  nan,
  241.0,
  42.0,
  39.0,
  26.0,
  6.0,
  5.0,
  70.0,
  14.0,
  173.0,
  27.0,
  2.0,
  36.0,
  397.0,
  183.0,
  155.0,
  10.0,
  144.0,
  60.0,
  31.0,
  320.0,
  548.0,
  617.0,
  58.0,
  160.0,
  529.0,
  829.0,
  1140.0,
  13.0,
  29.0,
  83.0,
  273.0,
  378.0,
  8.0,
  3.0,
  473.0,
  4.0,
  248.0,
  95.0,
  59.0,
  37.0,
  46.0,
  301.0,
  480.0,
  9.0,
  401.0,
  34.0,
  252.0,
  597.0,
  25.0,
  7.0,
  308.0,
  576.0,
  667.0,
  169.0,
  65.0,
  12.0,
  145.0,
  177.0,
  16.0,
  79.0,
  80.0,
  342.0,
  92.0,
  185.0,
  19.0,
  544.0,
  661.0,
  72.0,
  335.0,
  349.0,
  53.0,
  562.0,
  766.0,
  61.0,
  33.0,
  88.0,
  45.0,
  289.0,
  250.0,
  195.0,
  186.0,
  98.0,
  509.0,
  917.0,
  89.0,
  140.0,
  52.0,
  129.0,
  121.0,
  17.0,
  117.0,
  68.0,
  43.0,
  130.0,
  315.0,
  1120.0,
  104.0,
  119.0,
  11.0,
  1150.0,
  295.0,
  120.0,
  524.0,
  142.0,
  396.0,
  67.0,
  375.0,
  125.0,
  164.0,
  213.0,
  458.0],
 'minimum_wage': [0.43,
  1.12,
  0.95,
  6.63,
  0.71,
  3.04,
  3.35,
  0.66,
  13.59,
  nan,
  0.47,
  5.25,
  0.51,
  3.13,
  1.49,
  10.31,
  1.65,
  0.39,
  0.32,
  1.36,
  1.04,
  0.29,
  1.53,
  1.57,
  0.34,
  0.36,
  0.68,
  0.35,
  9.51,
  0.37,
  0.6,
  2.0,
  0.87,
  1.23,
  0.88,
  1.84,
  2.92,
  0.05,
  3.0,
  0.18,
  1.48,
  0.4,
  2.46,
  0.5,
  1.05,
  3.14,
  1.28,
  11.16,
  1.46,
  0.13,
  9.99,
  0.27,
  4.46,
  1.6,
  0.16,
  0.98,
  0.25,
  1.01,
  2.62,
  0.3,
  0.48,
  1.58,
  1.24,
  10.79,
  7.58,
  1.33,
  6.77,
  0.41,
  0.09,
  0.83,
  2.8,
  2.15,
  0.17,
  1.88,
  2.41,
  13.05,
  0.21,
  0.12,
  0.93,
  0.23,
  5.07,
  0.53,
  0.38,
  0.49,
  0.31,
  11.72,
  0.65,
  10.29,
  11.49,
  0.54,
  4.33,
  0.69,
  1.16,
  1.55,
  2.93,
  3.78,
  2.25,
  3.33,
  0.78,
  3.85,
  0.57,
  3.11,
  6.49,
  5.6,
  1.02,
  1.06,
  3.45,
  0.01,
  0.84,
  10.13,
  7.25,
  1.66,
  0.24,
  1.56,
  0.73],
 'out_of_pocket_health_expenditure': [78.4,
  56.9,
  28.1,
  36.4,
  33.4,
  24.3,
  17.6,
  81.6,
  19.6,
  17.9,
  78.6,
  27.8,
  25.1,
  71.8,
  45.2,
  34.5,
  22.7,
  40.5,
  19.8,
  25.9,
  28.6,
  5.3,
  28.3,
  6.0,
  47.7,
  36.1,
  19.1,
  36.0,
  23.2,
  59.4,
  69.7,
  14.6,
  39.6,
  56.4,
  32.2,
  32.4,
  18.3,
  74.8,
  43.8,
  21.5,
  15.2,
  nan,
  43.9,
  14.8,
  37.4,
  13.7,
  20.4,
  28.4,
  43.7,
  62.0,
  27.9,
  72.0,
  52.4,
  22.8,
  11.3,
  37.8,
  21.4,
  19.9,
  6.8,
  20.3,
  57.3,
  12.5,
  35.5,
  57.0,
  55.8,
  54.5,
  37.2,
  36.3,
  49.1,
  29.0,
  17.0,
  65.1,
  48.3,
  39.7,
  76.5,
  24.4,
  23.7,
  13.1,
  38.8,
  0.2,
  14.4,
  48.2,
  45.4,
  41.6,
  32.1,
  16.9,
  36.7,
  10.6,
  21.7,
  11.0,
  16.4,
  46.3,
  37.1,
  10.0,
  50.7,
  41.4,
  2.5,
  46.2,
  6.1,
  39.3,
  31.8,
  53.1,
  73.9,
  8.3,
  60.4,
  12.3,
  12.6,
  52.3,
  72.2,
  35.6,
  14.3,
  6.4,
  66.5,
  21.8,
  30.5,
  5.8,
  36.5,
  30.9,
  53.5,
  27.7,
  6.2,
  21.3,
  26.0,
  56.6,
  48.4,
  11.5,
  11.7,
  15.0,
  44.2,
  40.6,
  38.2,
  18.4,
  3.3,
  7.7,
  36.8,
  61.3,
  24.2,
  38.4,
  63.2,
  10.1,
  53.7,
  63.1,
  26.1,
  11.8,
  10.2,
  51.0,
  37.3,
  39.8,
  71.1,
  0.7,
  47.8,
  17.8,
  11.1,
  16.2,
  42.7,
  8.9,
  45.8,
  43.5,
  81.0,
  27.5,
  25.8],
 'physicians_per_thousand': [0.28,
  1.2,
  1.72,
  3.33,
  0.21,
  2.76,
  3.96,
  4.4,
  3.68,
  5.17,
  3.45,
  1.94,
  0.93,
  0.58,
  2.48,
  5.19,
  3.07,
  1.12,
  0.08,
  0.42,
  1.59,
  2.16,
  0.37,
  2.15,
  1.61,
  4.03,
  0.1,
  0.23,
  0.77,
  0.17,
  0.09,
  2.61,
  0.06,
  0.04,
  2.59,
  1.98,
  2.18,
  0.27,
  0.12,
  2.89,
  3.0,
  8.42,
  1.95,
  4.12,
  0.07,
  4.01,
  0.22,
  1.08,
  1.56,
  2.04,
  0.45,
  1.57,
  0.4,
  4.48,
  nan,
  0.84,
  3.81,
  3.27,
  0.68,
  7.12,
  4.25,
  0.14,
  5.48,
  1.41,
  0.35,
  0.13,
  0.8,
  0.31,
  3.41,
  4.08,
  0.86,
  0.43,
  1.58,
  0.71,
  3.31,
  4.62,
  3.98,
  1.31,
  2.41,
  2.32,
  3.25,
  0.16,
  0.2,
  2.58,

In [32]:
df[nulos_esta_num].describe().T

,count,mean,std,min,25%,50%,75%,max
density,188.0,139.281915,158.208082,2.000000,33.500000,83.000000,203.0000,847.00
agricultural_land(_%),188.0,39.117553,21.783052,0.600000,21.700000,39.600000,55.3750,82.60
birth_rate,189.0,20.214974,9.945774,5.900000,11.300000,17.950000,28.7500,46.08
calling_code,194.0,360.546392,323.236419,1.000000,82.500000,255.500000,506.7500,1876.00
cpi,175.0,144.193600,54.783998,99.030000,113.670000,124.740000,155.9250,550.93
cpi_change_,179.0,6.722346,24.450414,-4.300000,1.000000,2.300000,4.2500,254.90
fertility_rate,188.0,2.698138,1.282267,0.980000,1.705000,2.245000,3.5975,6.91
forested_area_,188.0,32.015426,23.791331,0.000000,11.000000,32.000000,48.1750,98.30
gasoline_price,175.0,1.002457,0.368858,0.000000,0.755000,0.980000,1.2400,2.00
gross_primary_education_enrollment_,188.0,102.470213,13.151607,23.400000,98.950000,102.550000,108.0250,142.50
gross_tertiary_education_enrollment_,183.0,37.963388,29.261022,0.800000,12.150000,31.200000,63.1500,136.60
infant_mortality,189.0,21.332804,19.548058,1.400000,6.000000,14.000000,32.7000,84.50
life_expectancy,187.0,72.279679,7.483661,52.800000,67.000000,73.200000,77.5000,85.40
maternal_mortality_ratio,181.0,160.392265,233.502024,2.000000,13.000000,53.000000,186.0000,1150.00
minimum_wage,150.0,2.194133,2.970796,0.010000,0.402500,1.045000,2.4475,13.59
out_of_pocket_health_expenditure,188.0,32.637234,19.172697,0.200000,17.450000,30.700000,43.9750,81.60
physicians_per_thousand,188.0,1.839840,1.684261,0.010000,0.332500,1.460000,2.9350,8.42
population_labor_force_participation_,176.0,62.738068,10.502907,38.000000,56.150000,62.450000,69.5000,86.80
tax_revenue_,169.0,16.573964,6.961632,0.000000,11.700000,16.300000,21.1000,37.20
total_tax_rate,183.0,40.822404,20.557662,8.000000,30.600000,37.200000,48.0000,219.60
unemployment_rate,176.0,6.886364,5.079216,0.090000,3.395000,5.360000,9.4900,28.18
tax_density_ratio,178.0,1.382211,2.491192,0.035463,0.199579,0.440757,1.2775,15.80

In [36]:
col_mediana = ['maternal_mortality_ratio', 'calling_code', 'density']

In [38]:
# columnas que tienen un promedio muy diferente a la mediana, reemplazamos nulos por mediana
#hacemos un bucle
for col in col_mediana:
    mediana = df[col].median()
    print(f"La mediana de la columna '{col}' es: {round(mediana, 2)}")

    # aplicamos el método 'fillna()' a la columna
    df[col] = df[col].fillna(mediana)

    # comprobamos los nulos para la columna
    print(f"Después del 'fillna' tenemos {df[col].isnull().sum()} nulos")

La mediana de la columna 'maternal_mortality_ratio' es: 53.0
Después del 'fillna' tenemos 0 nulos
La mediana de la columna 'calling_code' es: 255.5
Después del 'fillna' tenemos 0 nulos
La mediana de la columna 'density' es: 83.0
Después del 'fillna' tenemos 0 nulos

In [39]:
nulos_esta_num

Index(['density', 'agricultural_land(_%)', 'birth_rate', 'calling_code', 'cpi',
       'cpi_change_', 'fertility_rate', 'forested_area_', 'gasoline_price',
       'gross_primary_education_enrollment_',
       'gross_tertiary_education_enrollment_', 'infant_mortality',
       'life_expectancy', 'maternal_mortality_ratio', 'minimum_wage',
       'out_of_pocket_health_expenditure', 'physicians_per_thousand',
       'population_labor_force_participation_', 'tax_revenue_',
       'total_tax_rate', 'unemployment_rate', 'tax_density_ratio'],
      dtype='object')

In [40]:
col_media = ['agricultural_land(_%)', 'birth_rate', 'cpi',
       'cpi_change_', 'fertility_rate', 'forested_area_', 'gasoline_price',
       'gross_primary_education_enrollment_',
       'gross_tertiary_education_enrollment_', 'infant_mortality',
       'life_expectancy', 'minimum_wage',
       'out_of_pocket_health_expenditure', 'physicians_per_thousand',
       'population_labor_force_participation_', 'tax_revenue_',
       'total_tax_rate', 'unemployment_rate', 'tax_density_ratio']

In [41]:
# columnas que tienen un promedio muy diferente a la mediana, reemplazamos nulos por mediana
#hacemos un bucle
for col in col_media:
    media = df[col].mean()
    print(f"La media de la columna '{col}' es: {round(media, 2)}")

    # aplicamos el método 'fillna()' a la columna
    df[col] = df[col].fillna(media)

    # comprobamos los nulos para la columna
    print(f"Después del 'fillna' tenemos {df[col].isnull().sum()} nulos")

La media de la columna 'agricultural_land(_%)' es: 39.12
Después del 'fillna' tenemos 0 nulos
La media de la columna 'birth_rate' es: 20.21
Después del 'fillna' tenemos 0 nulos
La media de la columna 'cpi' es: 144.19
Después del 'fillna' tenemos 0 nulos
La media de la columna 'cpi_change_' es: 6.72
Después del 'fillna' tenemos 0 nulos
La media de la columna 'fertility_rate' es: 2.7
Después del 'fillna' tenemos 0 nulos
La media de la columna 'forested_area_' es: 32.02
Después del 'fillna' tenemos 0 nulos
La media de la columna 'gasoline_price' es: 1.0
Después del 'fillna' tenemos 0 nulos
La media de la columna 'gross_primary_education_enrollment_' es: 102.47
Después del 'fillna' tenemos 0 nulos
La media de la columna 'gross_tertiary_education_enrollment_' es: 37.96
Después del 'fillna' tenemos 0 nulos
La media de la columna 'infant_mortality' es: 21.33
Después del 'fillna' tenemos 0 nulos
La media de la columna 'life_expectancy' es: 72.28
Después del 'fillna' tenemos 0 nulos
La media de la columna 'minimum_wage' es: 2.19
Después del 'fillna' tenemos 0 nulos
La media de la columna 'out_of_pocket_health_expenditure' es: 32.64
Después del 'fillna' tenemos 0 nulos
La media de la columna 'physicians_per_thousand' es: 1.84
Después del 'fillna' tenemos 0 nulos
La media de la columna 'population_labor_force_participation_' es: 62.74
Después del 'fillna' tenemos 0 nulos
La media de la columna 'tax_revenue_' es: 16.57
Después del 'fillna' tenemos 0 nulos
La media de la columna 'total_tax_rate' es: 40.82
Después del 'fillna' tenemos 0 nulos
La media de la columna 'unemployment_rate' es: 6.89
Después del 'fillna' tenemos 0 nulos
La media de la columna 'tax_density_ratio' es: 1.38
Después del 'fillna' tenemos 0 nulos

In [42]:
# Obtenemos la lista de columnas categóricas que tienen nulos
nulos_esta_cat = df[df.columns[df.isnull().any()]].select_dtypes(include = "O").columns
print("Las columnas categóricas que tienen nulos son : \n ")
print(nulos_esta_cat)

Las columnas categóricas que tienen nulos son :

Index(['abbreviation', 'capital/major_city', 'currency-code', 'largest_city',
       'official_language'],
      dtype='object')

In [43]:
# calcular el número de nulos que tenemos en cada una de las columnas numericas
df[nulos_esta_cat].isnull().sum() / df.shape[0]

abbreviation          0.035897
capital/major_city    0.015385
currency-code         0.076923
largest_city          0.030769
official_language     0.025641
dtype: float64

In [ ]:
def valores_unicos_por_columna(dataframe): 
    valores_unicos = {} 
    for columna in dataframe.columns: 
        valores_unicos[columna] = dataframe[columna].unique().tolist() 
    return valores_unicos

In [44]:
valores_cat = valores_unicos_por_columna(df[nulos_esta_cat])

In [45]:
valores_cat

{'abbreviation': ['AF',
  'AL',
  'DZ',
  'AD',
  'AO',
  'AG',
  'AR',
  'AM',
  'AU',
  'AT',
  'AZ',
  'BS',
  'BH',
  'BD',
  'BB',
  'BY',
  'BE',
  'BZ',
  'BJ',
  'BT',
  'BO',
  'BA',
  'BW',
  'BR',
  'BN',
  'BG',
  'BF',
  'BI',
  'CI',
  'CV',
  'KH',
  'CM',
  'CA',
  'CF',
  'TD',
  'CL',
  'CN',
  'CO',
  'KM',
  nan,
  'CR',
  'HR',
  'CU',
  'CY',
  'CZ',
  'CD',
  'DK',
  'DJ',
  'DM',
  'DO',
  'EC',
  'EG',
  'SV',
  'GQ',
  'ER',
  'EE',
  'ET',
  'FJ',
  'FI',
  'FR',
  'GA',
  'GM',
  'GE',
  'DE',
  'GH',
  'GR',
  'GD',
  'GT',
  'GN',
  'GW',
  'GY',
  'HT',
  'HN',
  'HU',
  'IS',
  'IN',
  'ID',
  'IR',
  'IQ',
  'IL',
  'IT',
  'JM',
  'JP',
  'JO',
  'KZ',
  'KE',
  'KI',
  'KW',
  'KG',
  'LA',
  'LV',
  'LB',
  'LS',
  'LR',
  'LY',
  'LI',
  'LT',
  'LU',
  'MG',
  'MW',
  'MY',
  'MV',
  'ML',
  'MT',
  'MH',
  'MR',
  'MU',
  'MX',
  'FM',
  'MD',
  'MC',
  'MN',
  'ME',
  'MA',
  'MZ',
  'MM',
  'NR',
  'NP',
  'NL',
  'NZ',
  'NI',
  'NE',
  'NG',
  'KP',
  'NO',
  'OM',
  'PK',
  'PW',
  'PA',
  'PG',
  'PY',
  'PE',
  'PH',
  'PL',
  'PT',
  'QA',
  'RO',
  'RU',
  'RW',
  'KN',
  'LC',
  'VC',
  'WS',
  'SM',
  'ST',
  'SA',
  'SN',
  'RS',
  'SC',
  'SL',
  'SG',
  'SK',
  'SI',
  'SB',
  'SO',
  'ZA',
  'KR',
  'SS',
  'ES',
  'LK',
  'SD',
  'SR',
  'SE',
  'CH',
  'SY',
  'TJ',
  'TZ',
  'TH',
  'TL',
  'TG',
  'TO',
  'TT',
  'TN',
  'TR',
  'TM',
  'TV',
  'UG',
  'UA',
  'AE',
  'GB',
  'US',
  'UY',
  'UZ',
  'VU',
  'VE',
  'VN',
  'YE',
  'ZM',
  'ZW'],
 'capital/major_city': ['Kabul',
  'Tirana',
  'Algiers',
  'Andorra la Vella',
  'Luanda',
  "St. John's, Saint John",
  'Buenos Aires',
  'Yerevan',
  'Canberra',
  'Vienna',
  'Baku',
  'Nassau, Bahamas',
  'Manama',
  'Dhaka',
  'Bridgetown',
  'Minsk',
  'City of Brussels',
  'Belmopan',
  'Porto-Novo',
  'Thimphu',
  'Sucre',
  'Sarajevo',
  'Gaborone',
  'Bras���',
  'Bandar Seri Begawan',
  'Sofia',
  'Ouagadougou',
  'Bujumbura',
  'Yamoussoukro',
  'Praia',
  'Phnom Penh',
  'Yaound�',
  'Ottawa',
  'Bangui',
  "N'Djamena",
  'Santiago',
  'Beijing',
  'Bogot�',
  'Moroni, Comoros',
  'Brazzaville',
  'San Jos������',
  'Zagreb',
  'Havana',
  'Nicosia',
  'Prague',
  'Kinshasa',
  'Copenhagen',
  'Djibouti City',
  'Roseau',
  'Santo Domingo',
  'Quito',
  'Cairo',
  'San Salvador',
  'Malabo',
  'Asmara',
  'Tallinn',
  'Mbabane',
  'Addis Ababa',
  'Suva',
  'Helsinki',
  'Paris',
  'Libreville',
  'Banjul',
  'Tbilisi',
  'Berlin',
  'Accra',
  'Athens',
  "St. George's, Grenada",
  'Guatemala City',
  'Conakry',
  'Bissau',
  'Georgetown, Guyana',
  'Port-au-Prince',
  'Vatican City',
  'Tegucigalpa',
  'Budapest',
  'Reykjav��',
  'New Delhi',
  'Jakarta',
  'Tehran',
  'Baghdad',
  'Dublin',
  'Jerusalem',
  'Rome',
  'Kingston, Jamaica',
  'Tokyo',
  'Amman',
  'Astana',
  'Nairobi',
  'South Tarawa',
  'Kuwait City',
  'Bishkek',
  'Vientiane',
  'Riga',
  'Beirut',
  'Maseru',
  'Monrovia',
  nan,
  'Vaduz',
  'Vilnius',
  'Luxembourg City',
  'Antananarivo',
  'Lilongwe',
  'Kuala Lumpur',
  'Mal�',
  'Bamako',
  'Valletta',
  'Majuro',
  'Nouakchott',
  'Port Louis',
  'Mexico City',
  'Palikir',
  'Chi����',
  'Monaco City',
  'Ulaanbaatar',
  'Podgorica',
  'Rabat',
  'Maputo',
  'Naypyidaw',
  'Windhoek',
  'Yaren District',
  'Kathmandu',
  'Amsterdam',
  'Wellington',
  'Managua',
  'Niamey',
  'Abuja',
  'Pyongyang',
  'Skopje',
  'Oslo',
  'Muscat',
  'Islamabad',
  'Ngerulmud',
  'Panama City',
  'Port Moresby',
  'Asunci��',
  'Lima',
  'Manila',
  'Warsaw',
  'Lisbon',
  'Doha',
  'Bucharest',
  'Moscow',
  'Kigali',
  'Basseterre',
  'Castries',
  'Kingstown',
  'Apia',
  'City of San Marino',
  'S����',
  'Riyadh',
  'Dakar',
  'Belgrade',
  'Victoria, Seychelles',
  'Freetown',
  'Bratislava',
  'Ljubljana',
  'Honiara',
  'Mogadishu',
  'Pretoria',
  'Seoul',
  'Juba',
  'Madrid',
  'Colombo',
  'Khartoum',
  'Paramaribo',
  'Stockholm',
  'Bern',
  'Damascus',
  'Dushanbe',
  'Dodoma',
  'Bangkok',
  'Dili',
  'Lom�',
  'Nuku����',
  'Port of Spain',
  'Tunis',
  'Ankara',
  'Ashgabat',
  'Funafuti',
  'Kampala',
  'Kyiv',
  'Abu Dhabi',
  'London',
  'Washington, D.C.',
  'Montevideo',
  'Tashkent',
  'Port Vila',
  'Caracas',
  'Hanoi',
  'Sanaa',
  'Lusaka',
  'Harare'],
 'currency-code': ['AFN',
  'ALL',
  'DZD',
  'EUR',
  'AOA',
  'XCD',
  'ARS',
  'AMD',
  'AUD',
  'AZN',
  nan,
  'BHD',
  'BDT',
  'BBD',
  'BYN',
  'BZD',
  'XOF',
  'BOB',
  'BAM',
  'BWP',
  'BRL',
  'BND',
  'BGN',
  'BIF',
  'CVE',
  'XAF',
  'CAD',
  'CLP',
  'CNY',
  'COP',
  'KMF',
  'CRC',
  'HRK',
  'CUP',
  'CZK',
  'CDF',
  'DKK',
  'DJF',
  'DOP',
  'USD',
  'EGP',
  'ERN',
  'ETB',
  'FJD',
  'GMD',
  'GEL',
  'GHS',
  'GTQ',
  'GNF',
  'GYD',
  'HTG',
  'HNL',
  'HUF',
  'ISK',
  'INR',
  'IDR',
  'IRR',
  'IQD',
  'ILS',
  'JMD',
  'JOD',
  'KZT',
  'KES',
  'KWD',
  'KGS',
  'LAK',
  'LBP',
  'LYD',
  'CHF',
  'MGA',
  'MWK',
  'MYR',
  'MRU',
  'MUR',
  'MXN',
  'MDL',
  'MNT',
  'MAD',
  'MZN',
  'MMK',
  'NPR',
  'NZD',
  'NIO',
  'NGN',
  'KPW',
  'MKD',
  'NOK',
  'OMR',
  'PKR',
  'PGK',
  'PYG',
  'PEN',
  'PHP',
  'PLN',
  'QAR',
  'RON',
  'RUB',
  'RWF',
  'WST',
  'STN',
  'SAR',
  'RSD',
  'SCR',
  'SLL',
  'SGD',
  'SBD',
  'SOS',
  'ZAR',
  'KRW',
  'SSP',
  'LKR',
  'SDG',
  'SRD',
  'SEK',
  'SYP',
  'TJS',
  'TZS',
  'THB',
  'TOP',
  'TTD',
  'TND',
  'TRY',
  'TMT',
  'UGX',
  'UAH',
  'AED',
  'GBP',
  'UYU',
  'UZS',
  'VUV',
  'VED',
  'VND',
  'YER',
  'ZMW'],
 'largest_city': ['Kabul',
  'Tirana',
  'Algiers',
  'Andorra la Vella',
  'Luanda',
  "St. John's, Saint John",
  'Buenos Aires',
  'Yerevan',
  'Sydney',
  'Vienna',
  'Baku',
  'Nassau, Bahamas',
  'Riffa',
  'Dhaka',
  'Bridgetown',
  'Minsk',
  'Brussels',
  'Belize City',
  'Cotonou',
  'Thimphu',
  'Santa Cruz de la Sierra',
  'Tuzla Canton',
  'Gaborone',
  'S����',
  nan,
  'Sofia',
  'Ouagadougou',
  'Bujumbura',
  'Abidjan',
  'Praia',
  'Phnom Penh',
  'Douala',
  'Toronto',
  'Bangui',
  "N'Djamena",
  'Santiago',
  'Shanghai',
  'Bogot�',
  'Moroni, Comoros',
  'Brazzaville',
  'San Jos������',
  'Zagreb',
  'Havana',
  'Statos�������',
  'Prague',
  'Kinshasa',
  'Copenhagen',
  'Djibouti City',
  'Roseau',
  'Santo Domingo',
  'Quito',
  'Cairo',
  'San Salvador',
  'Malabo',
  'Asmara',
  'Tallinn',
  'Mbabane',
  'Addis Ababa',
  'Suva',
  'Helsinki',
  'Paris',
  'Libreville',
  'Serekunda',
  'Tbilisi',
  'Berlin',
  'Accra',
  'Macedonia',
  "St. George's, Grenada",
  'Guatemala City',
  'Kankan',
  'Bissau',
  'Georgetown, Guyana',
  'Port-au-Prince',
  'Tegucigalpa',
  'Budapest',
  'Reykjav��',
  'Kurebhar',
  'Kalimantan',
  'Tehran',
  'Baghdad',
  'Connacht',
  'Jerusalem',
  'Rome',
  'Kingston, Jamaica',
  'Tokyo',
  'Amman',
  'Almaty',
  'Nairobi',
  'South Tarawa',
  'Kuwait City',
  'Bishkek',
  'Vientiane',
  'Riga',
  'Tripoli, Lebanon',
  'Maseru',
  'Monrovia',
  'Schaan',
  'Vilnius',
  'Luxembourg City',
  'Antananarivo',
  'Lilongwe',
  'Johor Bahru',
  'Mal�',
  'Bamako',
  'Birkirkara',
  'Majuro',
  'Nouakchott',
  'Port Louis',
  'Mexico City',
  'Palikir',
  'Chi����',
  'Monaco City',
  'Ulaanbaatar',
  'Podgorica',
  'Casablanca',
  'Maputo',
  'Yangon',
  'Windhoek',
  'Kathmandu',
  'Amsterdam',
  'Auckland',
  'Managua',
  'Niamey',
  'Lagos',
  'Pyongyang',
  'Skopje',
  'Oslo',
  'Seeb',
  'Karachi',
  'Koror',
  'Panama City',
  'Port Moresby',
  'Ciudad del Este',
  'Lima',
  'Manila',
  'Warsaw',
  'Lisbon',
  'Doha',
  'Bucharest',
  'Moscow',
  'Kigali',
  'Basseterre',
  'Castries',
  'Calliaqua',
  'Apia',
  'City of San Marino',
  'Riyadh',
  'Pikine',
  'Belgrade',
  'Victoria, Seychelles',
  'Freetown',
  'Bratislava',
  'Ljubljana',
  'Honiara',
  'Bosaso',
  'Johannesburg',
  'Seoul',
  'Juba',
  'Madrid',
  'Colombo',
  'Omdurman',
  'Paramaribo',
  'S�����',
  'Z���',
  'Damascus',
  'Dushanbe',
  'Dar es Salaam',
  'Bangkok',
  'Dili',
  'Lom�',
  'Nuku����',
  'Chaguanas',
  'Tunis',
  'Istanbul',
  'Ashgabat',
  'Singapore',
  'Buganda',
  'Kyiv',
  'Dubai',
  'London',
  'New York City',
  'Montevideo',
  'Tashkent',
  'Port Vila',
  'Caracas',
  'Ho Chi Minh City',
  'Sanaa',
  'Lusaka',
  'Harare'],
 'official_language': ['Pashto',
  'Albanian',
  'Arabic',
  'Catalan',
  'Portuguese',
  'English',
  'Spanish',
  'Armenian',
  nan,
  'German',
  'Azerbaijani language',
  'Bengali',
  'Russian',
  'French',
  'Dzongkha',
  'Bosnian',
  'Malay',
  'Bulgarian',
  'Kirundi',
  'Khmer language',
  'Standard Chinese',
  'Croatian',
  'Greek',
  'Czech',
  'Danish',
  'Modern Standard Arabic',
  'Tigrinya',
  'Estonian',
  'Amharic',
  'Fiji Hindi',
  'Swedish',
  'Georgian',
  'Italian',
  'Hungarian',
  'Icelandic',
  'Hindi',
  'Indonesian',
  'Persian',
  'Irish',
  'Hebrew',
  'Jamaican English',
  'Swahili',
  'Lao',
  'Latvian',
  'Lithuanian',
  'Luxembourgish',
  'Malaysian language',
  'Divehi',
  'Maltese',
  'Marshallese',
  'Romanian',
  'Mongolian',
  'Montenegrin language',
  'Burmese',
  'Nepali',
  'Dutch',
  'Korean',
  'Macedonian',
  'Norwegian',
  'Urdu',
  'Tok Pisin',
  'Polish',
  'Samoan',
  'Serbian',
  'Slovak',
  'Slovene language',
  'Afrikaans',
  'Tamil',
  'Thai',
  'Tongan Language',
  'Turkish',
  'Turkmen',
  'Tuvaluan Language',
  'Ukrainian',
  'Uzbek',
  'Vietnamese',
  'Shona']}

In [46]:
df[nulos_esta_cat].describe().T

                   count unique      top freq
abbreviation         188    188       AF    1
capital/major_city   192    192    Kabul    1
currency-code        180    133      EUR   23
largest_city         189    188    S����    2
official_language    190     76  English   31

In [47]:
# sacamos el 'value_counts()' de cada una de las columnas categóricas que tienen nulos 
#para saber como es la distribución de sus categorías
for col in nulos_esta_cat:
    print(f"La distribución de las categorías para la columna {col.upper()}")
    display(df[col].value_counts() / df.shape[0])  # display es una función utilizada para mostrar objetos de manera más legible en Jupyter Notebooks o entornos similares. 
    print("........................")

La distribución de las categorías para la columna ABBREVIATION

abbreviation
AF    0.005128
PY    0.005128
NE    0.005128
NG    0.005128
KP    0.005128
        ...
GR    0.005128
GD    0.005128
GT    0.005128
GN    0.005128
ZW    0.005128
Name: count, Length: 188, dtype: float64

........................
La distribución de las categorías para la columna CAPITAL/MAJOR_CITY

capital/major_city
Kabul                    0.005128
Tirana                   0.005128
Wellington               0.005128
Managua                  0.005128
Niamey                   0.005128
                           ...
Athens                   0.005128
St. George's, Grenada    0.005128
Guatemala City           0.005128
Conakry                  0.005128
Harare                   0.005128
Name: count, Length: 192, dtype: float64

........................
La distribución de las categorías para la columna CURRENCY-CODE

currency-code
EUR    0.117949
XOF    0.041026
XCD    0.030769
USD    0.030769
XAF    0.025641
         ...
GMD    0.005128
FJD    0.005128
ETB    0.005128
ERN    0.005128
ZMW    0.005128
Name: count, Length: 133, dtype: float64

........................
La distribución de las categorías para la columna LARGEST_CITY

largest_city
S����                    0.010256
Panama City              0.005128
Managua                  0.005128
Niamey                   0.005128
Lagos                    0.005128
                           ...
Macedonia                0.005128
St. George's, Grenada    0.005128
Guatemala City           0.005128
Kankan                   0.005128
Harare                   0.005128
Name: count, Length: 188, dtype: float64

........................
La distribución de las categorías para la columna OFFICIAL_LANGUAGE

official_language
English             0.158974
French              0.128205
Spanish             0.097436
Arabic              0.092308
Portuguese          0.035897
                      ...
Albanian            0.005128
Jamaican English    0.005128
Lao                 0.005128
Latvian             0.005128
Shona               0.005128
Name: count, Length: 76, dtype: float64

........................

In [48]:
#columnas que cambiaremos por 'unknown'
col_desc = ['abbreviation', 'capital/major_city', 'largest_city']

In [49]:
# iteramos por la lista de columnas a las que le vamos a cambiar los nulos por "Uknown"
for columna in col_desc:
    
    # reemplazamos los nulos por el valor Unknown para cada una de las columnas de la lista
    df[columna] = df[columna].fillna("Unknown")
    
# comprobamos si quedan nulos en las columnas categóricas. 
print("Después del reemplazo usando 'fillna' quedan los siguientes nulos")
df[col_desc].isnull().sum()

Después del reemplazo usando 'fillna' quedan los siguientes nulos

abbreviation          0
capital/major_city    0
largest_city          0
dtype: int64

In [52]:
#columnas que cambiaremos por la moda
col_moda = ['currency-code', 'official_language']

In [53]:
# iteramos por la lista creada en el paso anterior:
for columna in col_moda:
    
    # calculamos la moda para la columna por la que estamos iterando
    moda = df[columna].mode()[0]    
    
    # utilizando el método fillna reemplazamos los valores nulos por la moda calculada en el paso anterior. 
    df[columna] = df[columna].fillna(moda)

# por último chequeamos si se han eliminado los nulos en las columnas de "marital" y "loan"
print("Después del reemplazo usando 'fillna' quedan los siguientes nulos")

df[col_moda].isnull().sum()

Después del reemplazo usando 'fillna' quedan los siguientes nulos

currency-code        0
official_language    0
dtype: int64

In [54]:
df.to_csv("world_data_nuevo.csv")